spring:
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false

    mustache:
        suffix: .html

    security:
        user:
            name: test
            password: test

    main:
        allow-bean-definition-overriding: true

spring.jpa.generate-ddl: true
spring.jpa.properties.hibernate.dialect: com.hedvig.paymentservice.PostgresDialect

graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
        actuator-metrics: true

graphiql:
    mapping: /graphiql
    endpoint:
        graphql: /graphql
    enabled: true
    pageTitle: Payment-service GraphiQL

hedvig:
    adyen:
        public:
            key: test
        allow3DS2: true
        allowTrustlyPayouts: true
        returnUrl: test
        merchantAccount: test
        enviroment: TEST
        apiKey: test
        urlPrefix: test
        charge:
            autorescue:
                scenario:

    trustly:
        validRedirectHosts: [ ]
        URLScheme: test
