spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

spring.jpa.generate-ddl: true
spring.jpa.properties.hibernate.dialect: com.hedvig.paymentservice.PostgresDialect


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: Payment GraphiQL

hedvig:
  trustly:
    validRedirectHosts: []
    URLScheme: test
