spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

spring.jpa.generate-ddl: true
spring.jpa.properties.hibernate.dialect: com.hedvig.paymentservice.PostgresDialect


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    actuator-metrics: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  enabled: true
  pageTitle: Payment-service GraphiQL


hedvig:
  trustly:
    validRedirectHosts: []
    URLScheme: test
